name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for submitting an issue against Avara! Someone will jump on your report ASAP. In the meantime, feel free to join us on IRC at avaraline.net or on [Matrix](https://matrix.to/#/!aIYRNfvpKSzEIwbtqn:vastan.net?via=vastan.net&via=matrix.org)'
        pr-message: 'Thanks for submitting a PR against Avara! Someone will jump on your report ASAP. In the meantime, feel free to join us on IRC at avaraline.net or on [Matrix](https://matrix.to/#/!aIYRNfvpKSzEIwbtqn:vastan.net?via=vastan.net&via=matrix.org)'
